server:
  port: 8080
  servlet:
    context-path: /photobook-demo
    
spring:

  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/photobook_demo}

  threads:
    virtual:
      enabled: true